data(Titanic)
data(UCBAdmissions)
data(HairEyeColor)
data(PreSex)
 
mosaic(Titanic)
mosaic(Titanic, shade = TRUE)
mosaic(~ Sex + Class, data = Titanic, shade = TRUE)
mosaic(~ Sex + Class + Survived, data = Titanic, shade = TRUE)
mosaic(~ PremaritalSex + ExtramaritalSex | MaritalStatus + Gender, data = PreSex)
mosaic(~ PremaritalSex + ExtramaritalSex | MaritalStatus + Gender, data = PreSex, labeling = labeling.conditional(abbreviate.varnames = TRUE))
mosaic(Titanic, spacing = spacing.increase())
mosaic(Titanic, spacing = spacing.equal())
mosaic(Titanic, labeling = labeling.text())
mosaic(Titanic, labeling = labeling.cells())
mosaic(Titanic, labeling = labeling.cells(abbreviate.labeling = TRUE))
mosaic(Titanic, labeling = labeling.cells(abbreviate.varnames = TRUE))
mosaic(Titanic, labeling = labeling.cells(abbreviate.varnames = TRUE, abbreviate.labeling = TRUE))
mosaic(Titanic, labeling = labeling.text(abbreviate = TRUE))
mosaic(Titanic, labeling = labeling.text(abbreviate = c(Survived = TRUE)))
mosaic(Titanic, labeling = labeling.text(rot.labeling = c(bottom = 45)))
mosaic(Titanic, labeling = labeling.text(tl.labeling = TRUE))
mosaic(Titanic, labeling = labeling.text(tl.labeling = TRUE, tl.varnames = FALSE))
mosaic(Titanic, labeling = labeling.text(tl.labeling = TRUE, tl.varnames = c(TRUE,TRUE,FALSE,FALSE), boxes = TRUE))
mosaic(Titanic, labeling = labeling.cboxed())
mosaic(Titanic, labeling = labeling.lboxed())
mosaic(Titanic, labeling = labeling.left())
mosaic(Titanic, labeling = labeling.list(), mar = c(2,2,4,2))
mosaic(Titanic, labeling = labeling.text(rep = FALSE))
mosaic(Titanic, labeling = labeling.text(labbl.varnames = c(TRUE,TRUE,FALSE,FALSE)))
mosaic(~ Gender + Admit | Dept, data = UCBAdmissions, labeling = labeling.conditional(labeling.varnames = TRUE, varnames = FALSE), keepAR = FALSE, split.vertical = c(Dept = TRUE))
doubledecker(Titanic)
assoc(Hair ~ Eye, data = HairEyeColor)
assoc(Hair ~ Eye, data = HairEyeColor, compress = FALSE)
assoc(HairEyeColor, labeling = labeling.lboxed())
pairs(Titanic, shade = TRUE)
pairs(Titanic, panel.upper = panel.assoc, shade = TRUE)
